<?xml version='1.0' encoding='ASCII'?>
<?program_dtd version="1"?>
<!DOCTYPE PROGRAM [
<!ELEMENT PROGRAM (DESCRIPTION? , INFO_SOURCE? , PROCESSOR? , COMPILER? , DATATYPES? , MEMORY_MAP? , REGISTER_VALUES? , CODE? , DATA? , EQUATES? , COMMENTS? , PROPERTIES? , BOOKMARKS? , PROGRAM_TREES? , PROGRAM_ENTRY_POINTS? , RELOCATION_TABLE? , SYMBOL_TABLE? , FUNCTIONS? , MARKUP? , EXT_LIBRARY_TABLE?)>
<!ATTLIST PROGRAM NAME CDATA #REQUIRED>
<!ATTLIST PROGRAM EXE_PATH CDATA #IMPLIED>
<!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
<!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>
<!ELEMENT DISPLAY_SETTINGS EMPTY>
<!ATTLIST DISPLAY_SETTINGS FORMAT (hex | decimal | octal | binary | char) #IMPLIED>
<!ATTLIST DISPLAY_SETTINGS SIGNED (y | n) #IMPLIED>
<!ATTLIST DISPLAY_SETTINGS ZERO_PAD (y | n) #IMPLIED>
<!ATTLIST DISPLAY_SETTINGS ENDIAN (big | little) #IMPLIED>
<!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR (y | n) #IMPLIED>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT REGULAR_CMT (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT (#PCDATA)>
<!ELEMENT INFO_SOURCE EMPTY>
<!ATTLIST INFO_SOURCE USER CDATA #IMPLIED>
<!ATTLIST INFO_SOURCE TOOL CDATA #IMPLIED>
<!ATTLIST INFO_SOURCE FILE CDATA #IMPLIED>
<!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>
<!ELEMENT PROCESSOR EMPTY>
<!ATTLIST PROCESSOR NAME CDATA #REQUIRED>
<!ATTLIST PROCESSOR FAMILY CDATA #IMPLIED>
<!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA #IMPLIED>
<!ATTLIST PROCESSOR ENDIAN (big | little) #IMPLIED>
<!ATTLIST PROCESSOR ADDRESS_MODEL CDATA #IMPLIED>
<!-- TODO: expand compiler tag --><!ELEMENT COMPILER EMPTY>
<!ATTLIST COMPILER NAME CDATA #REQUIRED>
<!ELEMENT MEMORY_MAP (MEMORY_SECTION)*>
<!ELEMENT MEMORY_SECTION (MEMORY_CONTENTS* | BIT_MAPPED?)>
<!ATTLIST MEMORY_SECTION NAME CDATA #REQUIRED>
<!ATTLIST MEMORY_SECTION START_ADDR CDATA #REQUIRED>
<!ATTLIST MEMORY_SECTION LENGTH CDATA #REQUIRED>
<!ATTLIST MEMORY_SECTION PERMISSIONS (r | w | x | rw | rx | wx | rwx) #IMPLIED>
<!ATTLIST MEMORY_SECTION VOLATILE (y | n) #IMPLIED>
<!ATTLIST MEMORY_SECTION COMMENT CDATA #IMPLIED>
<!ELEMENT MEMORY_CONTENTS EMPTY>
<!ATTLIST MEMORY_CONTENTS START_ADDR CDATA #IMPLIED>
<!ATTLIST MEMORY_CONTENTS FILE_NAME CDATA #REQUIRED>
<!ATTLIST MEMORY_CONTENTS FILE_OFFSET CDATA #REQUIRED>
<!ATTLIST MEMORY_CONTENTS LENGTH CDATA #IMPLIED>
<!ELEMENT BIT_MAPPED EMPTY>
<!ATTLIST BIT_MAPPED SOURCE_ADDRESS CDATA #REQUIRED>
<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE)*>
<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
<!ATTLIST REGISTER_VALUE_RANGE REGISTER CDATA #REQUIRED>
<!ATTLIST REGISTER_VALUE_RANGE VALUE CDATA #REQUIRED>
<!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
<!ATTLIST REGISTER_VALUE_RANGE LENGTH CDATA #REQUIRED>
<!ELEMENT CODE (CODE_BLOCK)*>
<!ELEMENT CODE_BLOCK EMPTY>
<!ATTLIST CODE_BLOCK START CDATA #REQUIRED>
<!ATTLIST CODE_BLOCK END CDATA #REQUIRED>
<!ELEMENT DATA (DEFINED_DATA)*>
<!ELEMENT DEFINED_DATA (TYPEINFO_CMT? , DISPLAY_SETTINGS?)>
<!ATTLIST DEFINED_DATA ADDRESS CDATA #REQUIRED>
<!ATTLIST DEFINED_DATA DATATYPE CDATA #REQUIRED>
<!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE CDATA #IMPLIED>
<!ATTLIST DEFINED_DATA SIZE CDATA #IMPLIED>
<!ELEMENT EQUATES (EQUATE_GROUP)*>
<!ELEMENT EQUATE_GROUP (REGULAR_CMT? , REPEATABLE_CMT? , DISPLAY_SETTINGS? , (EQUATE | BIT_MASK)*)>
<!ATTLIST EQUATE_GROUP NAME CDATA #IMPLIED>
<!ATTLIST EQUATE_GROUP BIT_FIELD (yes | no) #IMPLIED>
<!ELEMENT EQUATE (REGULAR_CMT? , REPEATABLE_CMT?)>
<!ATTLIST EQUATE NAME CDATA #REQUIRED>
<!ATTLIST EQUATE VALUE CDATA #REQUIRED>
<!ATTLIST EQUATE BIT_MASK CDATA #IMPLIED>
<!ELEMENT BIT_MASK (REGULAR_CMT? , REPEATABLE_CMT?)>
<!ATTLIST BIT_MASK NAME CDATA #REQUIRED>
<!ATTLIST BIT_MASK VALUE CDATA #REQUIRED>
<!ELEMENT COMMENTS (COMMENT)*>
<!ELEMENT COMMENT (#PCDATA)>
<!ATTLIST COMMENT ADDRESS CDATA #REQUIRED>
<!ATTLIST COMMENT TYPE (end-of-line | repeatable | pre | post | plate) #REQUIRED>
<!ELEMENT PROPERTIES (PROPERTY)*>
<!ELEMENT PROPERTY EMPTY>
<!ATTLIST PROPERTY NAME CDATA #REQUIRED>
<!ATTLIST PROPERTY ADDRESS CDATA #IMPLIED>
<!ATTLIST PROPERTY TYPE (string | long | int | double | void | bool | date | custom) #IMPLIED>
<!ATTLIST PROPERTY VALUE CDATA #IMPLIED>
<!ELEMENT BOOKMARKS (BOOKMARK)*>
<!ELEMENT BOOKMARK EMPTY>
<!ATTLIST BOOKMARK ADDRESS CDATA #REQUIRED>
<!ATTLIST BOOKMARK TYPE CDATA #IMPLIED>
<!ATTLIST BOOKMARK CATEGORY CDATA #IMPLIED>
<!ATTLIST BOOKMARK DESCRIPTION CDATA #IMPLIED>
<!ELEMENT PROGRAM_TREES (TREE)*>
<!ELEMENT TREE (FOLDER | FRAGMENT)*>
<!ATTLIST TREE NAME CDATA #REQUIRED>
<!ELEMENT FOLDER (FOLDER | FRAGMENT)*>
<!ATTLIST FOLDER NAME CDATA #REQUIRED>
<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
<!ATTLIST FRAGMENT NAME CDATA #REQUIRED>
<!ELEMENT ADDRESS_RANGE EMPTY>
<!ATTLIST ADDRESS_RANGE START CDATA #REQUIRED>
<!ATTLIST ADDRESS_RANGE END CDATA #REQUIRED>
<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT)*>
<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
<!ATTLIST PROGRAM_ENTRY_POINT ADDRESS CDATA #REQUIRED>
<!ELEMENT RELOCATION_TABLE (RELOCATION)*>
<!ELEMENT RELOCATION EMPTY>
<!ATTLIST RELOCATION ADDRESS CDATA #REQUIRED>
<!ATTLIST RELOCATION STATUS (UNKNOWN | SKIPPED | UNSUPPORTED | FAILURE | PARTIAL | APPLIED | APPLIED_OTHER) #IMPLIED>
<!-- STATUS defaults to APPLIED if BYTES specified and TYPE is non-zero  --><!-- STATUS defaults to APPLIED_OTHER if BYTES specified and TYPE is zero  --><!-- STATUS defaults to UNKNOWN if BYTES are not specified  --><!ATTLIST RELOCATION TYPE CDATA #REQUIRED>
<!ATTLIST RELOCATION VALUE CDATA #IMPLIED>
<!ATTLIST RELOCATION BYTES CDATA #IMPLIED>
<!ATTLIST RELOCATION SYMBOL_NAME CDATA #IMPLIED>
<!ELEMENT SYMBOL_TABLE (SYMBOL)*>
<!ELEMENT SYMBOL EMPTY>
<!ATTLIST SYMBOL ADDRESS CDATA #REQUIRED>
<!ATTLIST SYMBOL NAME CDATA #REQUIRED>
<!ATTLIST SYMBOL NAMESPACE CDATA #IMPLIED>
<!ATTLIST SYMBOL TYPE (global | local) #IMPLIED>
<!ATTLIST SYMBOL SOURCE_TYPE (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
<!ATTLIST SYMBOL PRIMARY (y | n) #IMPLIED>
<!ATTLIST SYMBOL MANGLED CDATA #IMPLIED>
<!ELEMENT FUNCTIONS (FUNCTION)*>
<!ELEMENT FUNCTION (RETURN_TYPE? , ADDRESS_RANGE* , REGULAR_CMT? , REPEATABLE_CMT? , TYPEINFO_CMT? , STACK_FRAME? , REGISTER_VAR*)>
<!ATTLIST FUNCTION ENTRY_POINT CDATA #REQUIRED>
<!ATTLIST FUNCTION NAME CDATA #IMPLIED>
<!-- TODO: create xml attrs for each known attribute type --><!ATTLIST FUNCTION LIBRARY_FUNCTION (y | n) #IMPLIED>
<!ELEMENT RETURN_TYPE EMPTY>
<!ATTLIST RETURN_TYPE DATATYPE CDATA #REQUIRED>
<!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE CDATA #IMPLIED>
<!ATTLIST RETURN_TYPE SIZE CDATA #IMPLIED>
<!ELEMENT STACK_FRAME (STACK_VAR)*>
<!ATTLIST STACK_FRAME LOCAL_VAR_SIZE CDATA #IMPLIED>
<!ATTLIST STACK_FRAME PARAM_OFFSET CDATA #IMPLIED>
<!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE CDATA #IMPLIED>
<!ATTLIST STACK_FRAME RETURN_ADDR_SIZE CDATA #IMPLIED>
<!ATTLIST STACK_FRAME BYTES_PURGED CDATA #IMPLIED>
<!ELEMENT STACK_VAR (REGULAR_CMT? , REPEATABLE_CMT?)>
<!ATTLIST STACK_VAR STACK_PTR_OFFSET CDATA #REQUIRED>
<!-- offset from the stack ptr value at function entry --><!ATTLIST STACK_VAR FRAME_PTR_OFFSET CDATA #IMPLIED>
<!ATTLIST STACK_VAR NAME CDATA #IMPLIED>
<!ATTLIST STACK_VAR DATATYPE CDATA #REQUIRED>
<!ATTLIST STACK_VAR DATATYPE_NAMESPACE CDATA #IMPLIED>
<!ATTLIST STACK_VAR SIZE CDATA #IMPLIED>
<!ELEMENT REGISTER_VAR (REGULAR_CMT)?>
<!ATTLIST REGISTER_VAR NAME CDATA #REQUIRED>
<!ATTLIST REGISTER_VAR REGISTER CDATA #REQUIRED>
<!ATTLIST REGISTER_VAR DATATYPE CDATA #IMPLIED>
<!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE CDATA #IMPLIED>
<!ELEMENT MARKUP (MEMORY_REFERENCE | STACK_REFERENCE | EXT_LIBRARY_REFERENCE | EQUATE_REFERENCE | MANUAL_OPERAND | MANUAL_INSTRUCTION)*>
<!-- An OPERAND_INDEX is omitted for a mnemonic reference    --><!-- The first operand is identified with OPERAND_INDEX=0 --><!ELEMENT MEMORY_REFERENCE EMPTY>
<!ATTLIST MEMORY_REFERENCE ADDRESS CDATA #REQUIRED>
<!ATTLIST MEMORY_REFERENCE OPERAND_INDEX CDATA #IMPLIED>
<!ATTLIST MEMORY_REFERENCE USER_DEFINED (y | n) #IMPLIED>
<!ATTLIST MEMORY_REFERENCE TO_ADDRESS CDATA #REQUIRED>
<!ATTLIST MEMORY_REFERENCE BASE_ADDRESS CDATA #IMPLIED>
<!ATTLIST MEMORY_REFERENCE PRIMARY (y | n) #IMPLIED>
<!ELEMENT STACK_REFERENCE EMPTY>
<!ATTLIST STACK_REFERENCE ADDRESS CDATA #REQUIRED>
<!ATTLIST STACK_REFERENCE OPERAND_INDEX CDATA #IMPLIED>
<!ATTLIST STACK_REFERENCE USER_DEFINED (y | n) #IMPLIED>
<!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA #REQUIRED>
<!-- offset from the stack ptr value at function entry --><!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA #IMPLIED>
<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
<!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS CDATA #REQUIRED>
<!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX CDATA #IMPLIED>
<!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED (y | n) #IMPLIED>
<!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME CDATA #REQUIRED>
<!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL CDATA #IMPLIED>
<!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL CDATA #IMPLIED>
<!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR CDATA #IMPLIED>
<!ELEMENT EQUATE_REFERENCE EMPTY>
<!ATTLIST EQUATE_REFERENCE ADDRESS CDATA #REQUIRED>
<!ATTLIST EQUATE_REFERENCE OPERAND_INDEX CDATA #IMPLIED>
<!ATTLIST EQUATE_REFERENCE NAME CDATA #REQUIRED>
<!ATTLIST EQUATE_REFERENCE VALUE CDATA #IMPLIED>
<!ELEMENT MANUAL_OPERAND (#PCDATA)>
<!ATTLIST MANUAL_OPERAND ADDRESS CDATA #REQUIRED>
<!ATTLIST MANUAL_OPERAND OPERAND_INDEX CDATA #REQUIRED>
<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
<!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>
<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY)*>
<!ELEMENT EXT_LIBRARY EMPTY>
<!ATTLIST EXT_LIBRARY NAME CDATA #REQUIRED>
<!ATTLIST EXT_LIBRARY PATH CDATA #IMPLIED>
<!-- ************************************************************* --><!--                                                               --><!--                Data DTD                                       --><!--                                                               --><!-- ************************************************************* --><!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>
<!ELEMENT MEMBER (REGULAR_CMT? , REPEATABLE_CMT? , DISPLAY_SETTINGS?)>
<!ATTLIST MEMBER OFFSET CDATA #REQUIRED>
<!ATTLIST MEMBER DATATYPE CDATA #REQUIRED>
<!ATTLIST MEMBER DATATYPE_NAMESPACE CDATA #IMPLIED>
<!ATTLIST MEMBER NAME CDATA #IMPLIED>
<!ATTLIST MEMBER SIZE CDATA #IMPLIED>
<!ELEMENT STRUCTURE (REGULAR_CMT? , REPEATABLE_CMT? , MEMBER*)>
<!ATTLIST STRUCTURE NAME CDATA #REQUIRED>
<!ATTLIST STRUCTURE NAMESPACE CDATA #IMPLIED>
<!ATTLIST STRUCTURE SIZE CDATA #IMPLIED>
<!ATTLIST STRUCTURE VARIABLE_LENGTH (y | n) #IMPLIED>
<!ELEMENT UNION (REGULAR_CMT? , REPEATABLE_CMT? , MEMBER*)>
<!ATTLIST UNION NAME CDATA #REQUIRED>
<!ATTLIST UNION NAMESPACE CDATA #IMPLIED>
<!ATTLIST UNION SIZE CDATA #IMPLIED>
<!ELEMENT FUNCTION_DEF (REGULAR_CMT? , REPEATABLE_CMT? , RETURN_TYPE? , PARAMETER*)>
<!ATTLIST FUNCTION_DEF NAME CDATA #REQUIRED>
<!ATTLIST FUNCTION_DEF NAMESPACE CDATA #IMPLIED>
<!ELEMENT PARAMETER (REGULAR_CMT? , REPEATABLE_CMT? , DISPLAY_SETTINGS?)>
<!ATTLIST PARAMETER ORDINAL CDATA #REQUIRED>
<!ATTLIST PARAMETER DATATYPE CDATA #REQUIRED>
<!ATTLIST PARAMETER DATATYPE_NAMESPACE CDATA #IMPLIED>
<!ATTLIST PARAMETER NAME CDATA #IMPLIED>
<!ATTLIST PARAMETER SIZE CDATA #IMPLIED>
<!ELEMENT TYPE_DEF (REGULAR_CMT? , REPEATABLE_CMT?)>
<!ATTLIST TYPE_DEF NAME CDATA #REQUIRED>
<!ATTLIST TYPE_DEF NAMESPACE CDATA #IMPLIED>
<!ATTLIST TYPE_DEF DATATYPE CDATA #REQUIRED>
<!ATTLIST TYPE_DEF DATATYPE_NAMESPACE CDATA #IMPLIED>
<!ELEMENT ENUM (REGULAR_CMT? , REPEATABLE_CMT? , DISPLAY_SETTINGS? , ENUM_ENTRY*)>
<!ATTLIST ENUM NAME CDATA #REQUIRED>
<!ATTLIST ENUM NAMESPACE CDATA #IMPLIED>
<!ATTLIST ENUM SIZE CDATA #IMPLIED>
<!ELEMENT ENUM_ENTRY (REGULAR_CMT? , REPEATABLE_CMT?)>
<!ATTLIST ENUM_ENTRY NAME CDATA #REQUIRED>
<!ATTLIST ENUM_ENTRY VALUE CDATA #REQUIRED>
<!ATTLIST ENUM_ENTRY COMMENT CDATA #REQUIRED>
]>
<PROGRAM NAME="Z27AG_JDM_5MT_1860B104.bin" EXE_PATH="/C:/Users/User/Documents/myroms/mmc/colt/Z27AG_JDM_5MT_1860B104.bin" EXE_FORMAT="Raw Binary" IMAGE_BASE="00000000">
    <INFO_SOURCE USER="User" TOOL="Ghidra 10.3.2" TIMESTAMP="Sun Aug 13 23:22:00 CEST 2023"/>
    <PROCESSOR NAME="M32R" LANGUAGE_PROVIDER="m32r:2:fp8000:default" ENDIAN="big"/>
    <DATATYPES>
        <STRUCTURE NAME="axis_desc" NAMESPACE="/" SIZE="0x6">
            <REGULAR_CMT>Axis Description</REGULAR_CMT>
            <MEMBER OFFSET="0x0" DATATYPE="fp_offset_pointer" DATATYPE_NAMESPACE="/" NAME="target" SIZE="0x2"/>
            <MEMBER OFFSET="0x2" DATATYPE="fp_offset_pointer" DATATYPE_NAMESPACE="/" NAME="source" SIZE="0x2"/>
            <MEMBER OFFSET="0x4" DATATYPE="uint16_t" DATATYPE_NAMESPACE="/" NAME="size" SIZE="0x2"/>
            <MEMBER OFFSET="0x6" DATATYPE="uint16_t[0]" DATATYPE_NAMESPACE="/" NAME="data" SIZE="0x0"/>
        </STRUCTURE>
        <TYPE_DEF NAME="fp_offset_pointer" NAMESPACE="/" DATATYPE="pointer16" DATATYPE_NAMESPACE="/"/>
        <TYPE_DEF NAME="int16_t" NAMESPACE="/types.h" DATATYPE="short" DATATYPE_NAMESPACE="/"/>
        <TYPE_DEF NAME="int8_t" NAMESPACE="/types.h" DATATYPE="char" DATATYPE_NAMESPACE="/"/>
        <STRUCTURE NAME="map_2d_i8_desc" NAMESPACE="/" SIZE="0x4">
            <REGULAR_CMT>2D map containing signed i8 values</REGULAR_CMT>
            <MEMBER OFFSET="0x0" DATATYPE="uint8_t" DATATYPE_NAMESPACE="/" NAME="dimensions" SIZE="0x1"/>
            <MEMBER OFFSET="0x1" DATATYPE="uint8_t" DATATYPE_NAMESPACE="/" NAME="offset" SIZE="0x1"/>
            <MEMBER OFFSET="0x2" DATATYPE="fp_offset_pointer" DATATYPE_NAMESPACE="/" NAME="axis" SIZE="0x2"/>
            <MEMBER OFFSET="0x4" DATATYPE="int8_t[0]" DATATYPE_NAMESPACE="/types.h" NAME="data" SIZE="0x0"/>
        </STRUCTURE>
        <STRUCTURE NAME="map_3d_u8_desc" NAMESPACE="/" SIZE="0x7">
            <REGULAR_CMT>2D map containing signed i8 values</REGULAR_CMT>
            <MEMBER OFFSET="0x0" DATATYPE="uint8_t" DATATYPE_NAMESPACE="/" NAME="dimensions" SIZE="0x1"/>
            <MEMBER OFFSET="0x1" DATATYPE="uint8_t" DATATYPE_NAMESPACE="/" NAME="offset" SIZE="0x1"/>
            <MEMBER OFFSET="0x2" DATATYPE="fp_offset_pointer" DATATYPE_NAMESPACE="/" NAME="xaxis" SIZE="0x2"/>
            <MEMBER OFFSET="0x4" DATATYPE="fp_offset_pointer" DATATYPE_NAMESPACE="/" NAME="yaxis" SIZE="0x2"/>
            <MEMBER OFFSET="0x6" DATATYPE="uint8_t" DATATYPE_NAMESPACE="/" NAME="xsize" SIZE="0x1"/>
            <MEMBER OFFSET="0x7" DATATYPE="uint8_t[0]" DATATYPE_NAMESPACE="/" NAME="data" SIZE="0x0"/>
        </STRUCTURE>
        <STRUCTURE NAME="run_state_flags_bits" NAMESPACE="/" SIZE="0x2">
            <MEMBER OFFSET="0x0" DATATYPE="uint16_t:1" DATATYPE_NAMESPACE="/" NAME="closed_loop" SIZE="0x1"/>
            <MEMBER OFFSET="0x1" DATATYPE="uint16_t:1" DATATYPE_NAMESPACE="/" NAME="closed_loop_copy" SIZE="0x1"/>
            <MEMBER OFFSET="0x1" DATATYPE="uint16_t:1" DATATYPE_NAMESPACE="/" NAME="always_on_x20" SIZE="0x1"/>
            <MEMBER OFFSET="0x1" DATATYPE="uint16_t:1" DATATYPE_NAMESPACE="/" NAME="stall" SIZE="0x1"/>
            <MEMBER OFFSET="0x1" DATATYPE="uint16_t:1" DATATYPE_NAMESPACE="/" NAME="engaged_fuel_cut" SIZE="0x1"/>
            <MEMBER OFFSET="0x1" DATATYPE="uint16_t:1" DATATYPE_NAMESPACE="/" NAME="maf_sensor_fault" SIZE="0x1"/>
            <MEMBER OFFSET="0x1" DATATYPE="uint16_t:1" DATATYPE_NAMESPACE="/" NAME="cranking" SIZE="0x1"/>
        </STRUCTURE>
        <TYPE_DEF NAME="uint16_t" NAMESPACE="/" DATATYPE="ushort" DATATYPE_NAMESPACE="/"/>
        <TYPE_DEF NAME="uint32_t" NAMESPACE="/" DATATYPE="uint" DATATYPE_NAMESPACE="/"/>
        <TYPE_DEF NAME="uint8_t" NAMESPACE="/" DATATYPE="uchar" DATATYPE_NAMESPACE="/"/>
    </DATATYPES>
    <MEMORY_MAP>
        <MEMORY_SECTION NAME="mem" START_ADDR="00000000" LENGTH="0xc0000" PERMISSIONS="rwx"/>
        <MEMORY_SECTION NAME="CS0" START_ADDR="00100000" LENGTH="0x100000" PERMISSIONS="rw"/>
        <MEMORY_SECTION NAME="CS1" START_ADDR="00200000" LENGTH="0x200000" PERMISSIONS="rw"/>
        <MEMORY_SECTION NAME="CS2" START_ADDR="00400000" LENGTH="0x200000" PERMISSIONS="rw"/>
        <MEMORY_SECTION NAME="CS3" START_ADDR="00600000" LENGTH="0x200000" PERMISSIONS="rw"/>
        <MEMORY_SECTION NAME="SFR" START_ADDR="00800000" LENGTH="0x4000" PERMISSIONS="rw"/>
        <MEMORY_SECTION NAME="RAM" START_ADDR="00804000" LENGTH="0x1c000" PERMISSIONS="rw"/>
    </MEMORY_MAP>
    <REGISTER_VALUES/>
    <CODE>
        <CODE_BLOCK START="00000000" END="00000083"/>
        <CODE_BLOCK START="00000090" END="00000093"/>
        <CODE_BLOCK START="00010000" END="000113f9"/>
        <CODE_BLOCK START="000113fc" END="00011865"/>
        <CODE_BLOCK START="00011868" END="000118af"/>
        <CODE_BLOCK START="00013d00" END="00013fd9"/>
        <CODE_BLOCK START="00013fdc" END="000141ef"/>
        <CODE_BLOCK START="000141f4" END="000142fd"/>
        <CODE_BLOCK START="00014300" END="0001440d"/>
        <CODE_BLOCK START="00014410" END="00014421"/>
        <CODE_BLOCK START="00014424" END="00014425"/>
        <CODE_BLOCK START="00014428" END="00014439"/>
        <CODE_BLOCK START="0001443c" END="0001443d"/>
        <CODE_BLOCK START="00014440" END="00014451"/>
        <CODE_BLOCK START="00014454" END="00014455"/>
        <CODE_BLOCK START="00014458" END="000144f5"/>
        <CODE_BLOCK START="000144f8" END="0001450f"/>
        <CODE_BLOCK START="00014538" END="000147bf"/>
        <CODE_BLOCK START="000147c4" END="000147cd"/>
        <CODE_BLOCK START="000147d0" END="000147d1"/>
        <CODE_BLOCK START="000147d4" END="00014aab"/>
        <CODE_BLOCK START="00014ab4" END="00014ca9"/>
        <CODE_BLOCK START="00014cac" END="00014cd5"/>
        <CODE_BLOCK START="00014cd8" END="00014d2d"/>
        <CODE_BLOCK START="00014d34" END="00014dd7"/>
        <CODE_BLOCK START="00014e04" END="00014e9b"/>
        <CODE_BLOCK START="00014ec0" END="00015009"/>
        <CODE_BLOCK START="0001500c" END="000152f9"/>
        <CODE_BLOCK START="000152fc" END="00015319"/>
        <CODE_BLOCK START="0001531c" END="00015339"/>
        <CODE_BLOCK START="0001533c" END="00015459"/>
        <CODE_BLOCK START="0001545c" END="00015541"/>
        <CODE_BLOCK START="000155cc" END="000155f3"/>
        <CODE_BLOCK START="000157c4" END="00015839"/>
        <CODE_BLOCK START="0001583c" END="00015a2d"/>
        <CODE_BLOCK START="00015a30" END="00016339"/>
        <CODE_BLOCK START="0001633c" END="0001634d"/>
        <CODE_BLOCK START="00016350" END="00016351"/>
        <CODE_BLOCK START="00016354" END="00016365"/>
        <CODE_BLOCK START="00016368" END="00016369"/>
        <CODE_BLOCK START="0001636c" END="0001637d"/>
        <CODE_BLOCK START="00016380" END="00016381"/>
        <CODE_BLOCK START="00016384" END="00016395"/>
        <CODE_BLOCK START="00016398" END="00016399"/>
        <CODE_BLOCK START="0001639c" END="000163f9"/>
        <CODE_BLOCK START="000163fc" END="000165c9"/>
        <CODE_BLOCK START="000165cc" END="000166f5"/>
        <CODE_BLOCK START="000166f8" END="000169e9"/>
        <CODE_BLOCK START="000169ec" END="00016b9d"/>
        <CODE_BLOCK START="00016bb8" END="00016c11"/>
        <CODE_BLOCK START="00016c14" END="00016cf1"/>
        <CODE_BLOCK START="00016cf4" END="00016e09"/>
        <CODE_BLOCK START="00016e0c" END="00016e89"/>
        <CODE_BLOCK START="00016e8c" END="00016f09"/>
        <CODE_BLOCK START="00016f0c" END="00016f89"/>
        <CODE_BLOCK START="00016f8c" END="00016fc1"/>
        <CODE_BLOCK START="00016fc4" END="00017205"/>
        <CODE_BLOCK START="00017208" END="00017389"/>
        <CODE_BLOCK START="0001743c" END="00017873"/>
        <CODE_BLOCK START="000178a4" END="00017939"/>
        <CODE_BLOCK START="0001793c" END="00017cc5"/>
        <CODE_BLOCK START="00017dac" END="00017dc9"/>
        <CODE_BLOCK START="00017e1c" END="00017e89"/>
        <CODE_BLOCK START="00017e8c" END="00017e95"/>
        <CODE_BLOCK START="00017e98" END="00017f7d"/>
        <CODE_BLOCK START="00017f80" END="00017f99"/>
        <CODE_BLOCK START="00017f9c" END="00017fd5"/>
        <CODE_BLOCK START="00017fd8" END="00017ffb"/>
        <CODE_BLOCK START="00018000" END="0001804d"/>
        <CODE_BLOCK START="00018050" END="000183d5"/>
        <CODE_BLOCK START="000183d8" END="000184d5"/>
        <CODE_BLOCK START="000184d8" END="00018a37"/>
        <CODE_BLOCK START="00018be0" END="00018c95"/>
        <CODE_BLOCK START="00018c98" END="00018cd1"/>
        <CODE_BLOCK START="00018cd4" END="00018cd9"/>
        <CODE_BLOCK START="00018cdc" END="00018ceb"/>
        <CODE_BLOCK START="00018d14" END="00018d65"/>
        <CODE_BLOCK START="00018d68" END="00018ea1"/>
        <CODE_BLOCK START="00018f00" END="00019305"/>
        <CODE_BLOCK START="0001930c" END="00019387"/>
        <CODE_BLOCK START="00019398" END="00019399"/>
        <CODE_BLOCK START="0001939c" END="0001948b"/>
        <CODE_BLOCK START="00019498" END="00019507"/>
        <CODE_BLOCK START="0001950c" END="0001952f"/>
        <CODE_BLOCK START="00019538" END="000198d1"/>
        <CODE_BLOCK START="000198d4" END="00019e41"/>
        <CODE_BLOCK START="00019e44" END="00019ea1"/>
        <CODE_BLOCK START="00019ea4" END="0001a27d"/>
        <CODE_BLOCK START="0001a358" END="0001a401"/>
        <CODE_BLOCK START="0001a404" END="0001a415"/>
        <CODE_BLOCK START="0001a418" END="0001a421"/>
        <CODE_BLOCK START="0001a424" END="0001a503"/>
        <CODE_BLOCK START="0001acdc" END="0001af21"/>
        <CODE_BLOCK START="0001af24" END="0001b009"/>
        <CODE_BLOCK START="0001b00c" END="0001b053"/>
        <CODE_BLOCK START="0001b100" END="0001b169"/>
        <CODE_BLOCK START="0001b16c" END="0001b16d"/>
        <CODE_BLOCK START="0001b1f4" END="0001b31d"/>
        <CODE_BLOCK START="0001b324" END="0001b4dd"/>
        <CODE_BLOCK START="0001b4e0" END="0001b619"/>
        <CODE_BLOCK START="0001b61c" END="0001b66d"/>
        <CODE_BLOCK START="0001b670" END="0001b671"/>
        <CODE_BLOCK START="0001b680" END="0001b711"/>
        <CODE_BLOCK START="0001b714" END="0001b723"/>
        <CODE_BLOCK START="0001b730" END="0001b755"/>
        <CODE_BLOCK START="0001b758" END="0001b769"/>
        <CODE_BLOCK START="0001b76c" END="0001b7d1"/>
        <CODE_BLOCK START="0001b7d4" END="0001b809"/>
        <CODE_BLOCK START="0001b810" END="0001b8e5"/>
        <CODE_BLOCK START="0001b8ec" END="0001b913"/>
        <CODE_BLOCK START="0001b920" END="0001b98d"/>
        <CODE_BLOCK START="0001b990" END="0001ba81"/>
        <CODE_BLOCK START="0001ba84" END="0001baf5"/>
        <CODE_BLOCK START="0001baf8" END="0001bcf9"/>
        <CODE_BLOCK START="0001bcfc" END="0001be37"/>
        <CODE_BLOCK START="0001be40" END="0001becb"/>
        <CODE_BLOCK START="0001bed0" END="0001bf25"/>
        <CODE_BLOCK START="0001bf28" END="0001c1bd"/>
        <CODE_BLOCK START="0001c22c" END="0001c4e5"/>
        <CODE_BLOCK START="0001c4e8" END="0001c4f1"/>
        <CODE_BLOCK START="0001c4f4" END="0001cd7f"/>
        <CODE_BLOCK START="0001ceb0" END="0001cfc1"/>
        <CODE_BLOCK START="0001cfc4" END="0001d195"/>
        <CODE_BLOCK START="0001d198" END="0001d3e9"/>
        <CODE_BLOCK START="0001d3ec" END="0001d489"/>
        <CODE_BLOCK START="0001d48c" END="0001d4ed"/>
        <CODE_BLOCK START="0001d4f0" END="0001d58d"/>
        <CODE_BLOCK START="0001d590" END="0001d941"/>
        <CODE_BLOCK START="0001d944" END="0001da55"/>
        <CODE_BLOCK START="0001da58" END="0001da81"/>
        <CODE_BLOCK START="0001da84" END="0001e1e9"/>
        <CODE_BLOCK START="0001e1ec" END="0001e589"/>
        <CODE_BLOCK START="0001e58c" END="0001ed01"/>
        <CODE_BLOCK START="0001ed04" END="0001ef15"/>
        <CODE_BLOCK START="0001ef18" END="0001efb5"/>
        <CODE_BLOCK START="0001efb8" END="0001f21d"/>
        <CODE_BLOCK START="0001f220" END="0001f275"/>
        <CODE_BLOCK START="0001f278" END="0001f29d"/>
        <CODE_BLOCK START="0001f2a0" END="0001f3b5"/>
        <CODE_BLOCK START="0001f3b8" END="0001f511"/>
        <CODE_BLOCK START="0001f514" END="0001f565"/>
        <CODE_BLOCK START="0001f568" END="0001f701"/>
        <CODE_BLOCK START="0001f704" END="0001f7dd"/>
        <CODE_BLOCK START="0001facc" END="0001fb25"/>
        <CODE_BLOCK START="0001fb28" END="0001fb61"/>
        <CODE_BLOCK START="0001fb64" END="000200d1"/>
        <CODE_BLOCK START="000200d4" END="000201e9"/>
        <CODE_BLOCK START="000201ec" END="00020291"/>
        <CODE_BLOCK START="00020294" END="00020315"/>
        <CODE_BLOCK START="00020318" END="00020355"/>
        <CODE_BLOCK START="00020358" END="000203e9"/>
        <CODE_BLOCK START="000203ec" END="00020485"/>
        <CODE_BLOCK START="00020488" END="000204e9"/>
        <CODE_BLOCK START="000204ec" END="0002052d"/>
        <CODE_BLOCK START="00020530" END="00020589"/>
        <CODE_BLOCK START="0002058c" END="00020621"/>
        <CODE_BLOCK START="00020624" END="00020651"/>
        <CODE_BLOCK START="00020654" END="00020a89"/>
        <CODE_BLOCK START="00020a90" END="00020ad1"/>
        <CODE_BLOCK START="00020ad4" END="00020afd"/>
        <CODE_BLOCK START="00020b00" END="00020bb9"/>
        <CODE_BLOCK START="00020bbc" END="00020bf1"/>
        <CODE_BLOCK START="00020bf4" END="00020c7d"/>
        <CODE_BLOCK START="00020c80" END="00020d4d"/>
        <CODE_BLOCK START="00020d50" END="00020e21"/>
        <CODE_BLOCK START="00020e24" END="00020ed1"/>
        <CODE_BLOCK START="00020ed4" END="00020f3d"/>
        <CODE_BLOCK START="00020f40" END="00020f61"/>
        <CODE_BLOCK START="00020f64" END="00020fb9"/>
        <CODE_BLOCK START="00020fbc" END="00021025"/>
        <CODE_BLOCK START="00021028" END="000210ad"/>
        <CODE_BLOCK START="000210b0" END="000210f1"/>
        <CODE_BLOCK START="000210f4" END="000211b9"/>
        <CODE_BLOCK START="000211bc" END="000213dd"/>
        <CODE_BLOCK START="000213e0" END="00021541"/>
        <CODE_BLOCK START="00021544" END="00021595"/>
        <CODE_BLOCK START="00021598" END="00021625"/>
        <CODE_BLOCK START="00021628" END="000216d1"/>
        <CODE_BLOCK START="000216d4" END="00021b0d"/>
        <CODE_BLOCK START="00021b10" END="00021dd1"/>
        <CODE_BLOCK START="00021dd4" END="00021dfd"/>
        <CODE_BLOCK START="00021e00" END="00021f09"/>
        <CODE_BLOCK START="00021f0c" END="000220cf"/>
        <CODE_BLOCK START="000222f0" END="00022525"/>
        <CODE_BLOCK START="00022528" END="000229b1"/>
        <CODE_BLOCK START="000229b4" END="00022aa5"/>
        <CODE_BLOCK START="00022aa8" END="00022b9d"/>
        <CODE_BLOCK START="00022ba0" END="00022e69"/>
        <CODE_BLOCK START="00022e6c" END="00022f85"/>
        <CODE_BLOCK START="00022f88" END="000230dd"/>
        <CODE_BLOCK START="000230e0" END="00023171"/>
        <CODE_BLOCK START="00023174" END="00023191"/>
        <CODE_BLOCK START="00023194" END="00023249"/>
        <CODE_BLOCK START="0002324c" END="000235e1"/>
        <CODE_BLOCK START="000235e4" END="000235e7"/>
        <CODE_BLOCK START="000235f0" END="00023619"/>
        <CODE_BLOCK START="0002361c" END="0002368d"/>
        <CODE_BLOCK START="00023690" END="000237c1"/>
        <CODE_BLOCK START="000237c4" END="00023b65"/>
        <CODE_BLOCK START="00023b68" END="00023c79"/>
        <CODE_BLOCK START="00023c7c" END="00023c9d"/>
        <CODE_BLOCK START="00023ca0" END="00023ca1"/>
        <CODE_BLOCK START="00023ca4" END="00023cdd"/>
        <CODE_BLOCK START="00023ce0" END="00023e01"/>
        <CODE_BLOCK START="00023e04" END="00023e51"/>
        <CODE_BLOCK START="00023e54" END="00023e5d"/>
        <CODE_BLOCK START="00023e60" END="00023e69"/>
        <CODE_BLOCK START="00023e6c" END="00024071"/>
        <CODE_BLOCK START="00024074" END="0002414d"/>
        <CODE_BLOCK START="00024150" END="00024319"/>
        <CODE_BLOCK START="0002431c" END="000244b9"/>
        <CODE_BLOCK START="000244bc" END="00024809"/>
        <CODE_BLOCK START="0002480c" END="00024941"/>
        <CODE_BLOCK START="00024944" END="00024a7d"/>
        <CODE_BLOCK START="00024a80" END="00024b69"/>
        <CODE_BLOCK START="00024b6c" END="00024c71"/>
        <CODE_BLOCK START="00024c74" END="00024ca9"/>
        <CODE_BLOCK START="00024cac" END="00024f49"/>
        <CODE_BLOCK START="00024f4c" END="00025081"/>
        <CODE_BLOCK START="00025084" END="00025311"/>
        <CODE_BLOCK START="00025314" END="000253c1"/>
        <CODE_BLOCK START="000253c4" END="000254b9"/>
        <CODE_BLOCK START="000254bc" END="000257e5"/>
        <CODE_BLOCK START="000257e8" END="00025891"/>
        <CODE_BLOCK START="00025894" END="00025c45"/>
        <CODE_BLOCK START="00025c48" END="00025ccd"/>
        <CODE_BLOCK START="00025cd0" END="00025e61"/>
        <CODE_BLOCK START="00025e64" END="00025ee9"/>
        <CODE_BLOCK START="00025eec" END="00026175"/>
        <CODE_BLOCK START="00026178" END="00026321"/>
        <CODE_BLOCK START="00026324" END="00026449"/>
        <CODE_BLOCK START="0002644c" END="00026591"/>
        <CODE_BLOCK START="00026594" END="000265d1"/>
        <CODE_BLOCK START="000265d4" END="000267b5"/>
        <CODE_BLOCK START="000267b8" END="0002684d"/>
        <CODE_BLOCK START="00026850" END="000269f3"/>
        <CODE_BLOCK START="00026a04" END="00026c79"/>
        <CODE_BLOCK START="00026c7c" END="00026cf1"/>
        <CODE_BLOCK START="00026cf4" END="00026d15"/>
        <CODE_BLOCK START="00026d18" END="00026d1d"/>
        <CODE_BLOCK START="00026d20" END="00027291"/>
        <CODE_BLOCK START="00027294" END="00027485"/>
        <CODE_BLOCK START="00027488" END="000275a1"/>
        <CODE_BLOCK START="000275a4" END="00027771"/>
        <CODE_BLOCK START="00027774" END="0002780d"/>
        <CODE_BLOCK START="00027810" END="000279d5"/>
        <CODE_BLOCK START="000279d8" END="00027d8b"/>
        <CODE_BLOCK START="00027e7c" END="00027eb1"/>
        <CODE_BLOCK START="00027eb4" END="000281a5"/>
        <CODE_BLOCK START="000281a8" END="00028229"/>
        <CODE_BLOCK START="0002822c" END="000286ad"/>
        <CODE_BLOCK START="000286b0" END="00028ab1"/>
        <CODE_BLOCK START="00028ab4" END="00028ba5"/>
        <CODE_BLOCK START="00028ba8" END="00028eb1"/>